=== GDWG-GSICS/Plotting_tool/war/server_resources/conf/conf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by EUMETSAT (EUMETSAT) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="configuration">
		<xs:annotation>
			<xs:documentation>Configuration of USC GSICS Plotting Tool.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="catalogs">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="catalog" type="CatalogType" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="global_attributes_names">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="filename" type="xs:string"/>
							<xs:element name="rad_to_tb_conv_formula" type="xs:string"/>
							<xs:element name="tb_to_rad_conv_formula" type="xs:string"/>
							<xs:element name="c1" type="xs:string"/>
							<xs:element name="c2" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="global_attributes_defaults">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="rad_to_tb_conv_formula" type="xs:string"/>
							<xs:element name="tb_to_rad_conv_formula" type="xs:string"/>
							<xs:element name="c1" type="xs:double"/>
							<xs:element name="c2" type="xs:double"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="variables_names">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="date" type="xs:string"/>
							<xs:element name="channel_name" type="xs:string"/>
							<xs:element name="offset" type="xs:string"/>
							<xs:element name="offset_se" type="xs:string"/>
							<xs:element name="slope" type="xs:string"/>
							<xs:element name="slope_se" type="xs:string"/>
							<xs:element name="covariance" type="xs:string"/>
							<xs:element name="std_scene_tb" type="xs:string"/>
							<xs:element name="alpha" type="xs:string"/>
							<xs:element name="beta" type="xs:string"/>
							<xs:element name="wnc" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="help_items">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="help_item" type="HelpItemType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CatalogType">
		<xs:annotation>
			<xs:documentation>Catalog Configuration</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="url" type="xs:string"/>
			<xs:element name="validate" type="xs:boolean"/>
		</xs:sequence>
		<xs:attribute name="name" use="required"/>
	</xs:complexType>
	<xs:complexType name="HelpItemType">
		<xs:annotation>
			<xs:documentation>Help Item</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="label" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="url" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== GDWG-GSICS/Plotting_tool/war/server_resources/conf/conf.val.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2005 rel. 3 U (http://www.altova.com) -->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="conf.xsd">
  <catalogs>
    <catalog name="EUMETSAT">
      <!-- Use of GSICS EUMETSAT THREDDS server's IP, to avoid problems with tool deployed in DMZ. -->
      <url>http://193.17.10.39/thredds/catalog.xml</url>
      <validate>false</validate>
    </catalog>
    <catalog name="VAL EUMETSAT">
      <!-- Use of VAL GSICS EUMETSAT THREDDS server's IP, to avoid problems with tool deployed in DMZ. -->
      <url>http://193.17.10.43/thredds/catalog.xml</url>
      <validate>false</validate>
    </catalog>
    <catalog name="NOAA">
      <url>http://gsics.nesdis.noaa.gov/thredds/catalog.xml</url>
      <validate>false</validate>
    </catalog>
    <catalog name="CMA">
      <url>http://gsics.nsmc.cma.gov.cn/thredds/catalog.xml</url>
      <validate>false</validate>
    </catalog>
  </catalogs>
  <global_attributes_names>
    <filename>id</filename>
    <rad_to_tb_conv_formula>radiance_to_brightness_conversion_formula</rad_to_tb_conv_formula>
    <tb_to_rad_conv_formula>brightness_to_radiance_conversion_formula</tb_to_rad_conv_formula>
    <c1>planck_function_constant_c1</c1>
    <c2>planck_function_constant_c2</c2>
  </global_attributes_names>
  <global_attributes_defaults>
			<rad_to_tb_conv_formula>((c2*wnc)/log(1+(c1*wnc^3)/radiance)-beta)/alpha</rad_to_tb_conv_formula>
			<tb_to_rad_conv_formula>(c1*wnc^3)/((exp(c2*wnc/(alpha*tb+beta)))-1)</tb_to_rad_conv_formula>
			<c1>1.19104e-5</c1> <!-- mW(cm^-1)^-4 m^-2 sr^-1 -->
			<c2>1.43877</c2> <!-- K cm -->
		</global_attributes_defaults>
  <variables_names>
    <date>date</date>
    <channel_name>channel_name</channel_name>
    <offset>offset</offset>
    <offset_se>offset_se</offset_se>
    <slope>slope</slope>
    <slope_se>slope_se</slope_se>
    <covariance>covariance</covariance>
    <std_scene_tb>std_scene_tb</std_scene_tb>
    <alpha>alpha</alpha>
    <beta>beta</beta>
    <wnc>wnc</wnc>
  </variables_names>
  <help_items>
    <help_item>
      <label>EUMETSAT GSICS Webpage</label>
      <description>GSICS information specific to the EUMETSAT GSICS products.</description>
      <url>http://www.eumetsat.int/website/home/Data/Products/Calibration/Intercalibration/index.html</url>
    </help_item>
    <help_item>
      <label>WMO GSICS Portal</label>
      <description>World Meteorological Organisation GSICS Portal, provide general information for the GSICS project.</description>
      <url>http://gsics.wmo.int</url>
    </help_item>
    <help_item>
      <label>GSICS GCC Portal</label>
      <description>The GSICS Coordination Centre Portal, coordination information, product catalogue and user messaging service can be found on this website.</description>
      <url>http://www.star.nesdis.noaa.gov/smcd/GCC/index.php</url>
    </help_item>
    <help_item>
      <label>EUMETSAT GSICS Server</label>
      <description>The EUMETSAT GSICS Data and Products Server.  Source data sets, collocation data sets and GSICS products can be viewed and downloaded from this server.</description>
      <url>http://gsics.eumetsat.int/thredds/catalog.html</url>
    </help_item>
  </help_items>
</configuration>
